# configs/config.yaml

train:
  data_path: "./dataset/processed"
  exp_name: "latent_dim128"
  batch_size: 1024
  epochs: 1000000
  lr: 0.001
  save_model_path: "./outputs/latent_dim128/"
  cond_dim: 26

generate:
  model_path: "./outputs/latent_space128.pth"
  output_dir: "./outputs/generated_images"
  num_images: 20
  name: "latent_space128.png"

vae_model:
  encoder_layers: [512, 256, 128]
  decoder_layers: [128, 256, 512]
  input_dim: 9216
  latent_dim: 128
  activation_function: "leaky_relu" 
